name: CI - Build y Verificación

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Dar permisos de ejecución a mvnw
        run: chmod +x mvnw

      - name: Compilar el proyecto con Maven
        run: ./mvnw clean install -DskipTests